// spec: identity-and-authorization/service-principal-assertions,
//       identity-and-authorization/token-lifetime-and-refresh,
//       identity-and-authorization/client-credential-custody,
//       identity-and-authorization/game-credential-scope
// The holder side of credential custody: how a Snek Centaur Server proves who
// it is, what it does with what it earns, and when it renews. The platform's
// verifying half lives in `packages/convex-host/convex/auth`.
//
// The credential's *lifetime* is deliberately not restated here — it is read
// off each credential's own `iat`/`exp`, so the number lives only in the
// minting code and a change there needs no coordinated change here.

import { SignJWT, decodeJwt } from "jose";

/**
 * ES256 (ECDSA on P-256). Why that algorithm and no other is recorded once, at
 * `packages/convex-host/convex/auth/credential.ts`. This package cannot depend
 * on the host — it is published to forks, which have no access to the
 * deployment's code — so the identifier is restated here, and
 * `credentials.contract.test.ts` in the host package feeds this function's real
 * output to the real verifier so the two cannot drift silently.
 */
const ALG = "ES256";

/**
 * An assertion has to survive only one call to the issuance endpoint, so its
 * lifetime is the network's, not a session's. The platform's single-use record
 * is the actual defence (`service-principal-assertions#replayed-assertion-refused`);
 * a lifetime this short is what lets that record be swept rather than retained
 * indefinitely.
 */
const ASSERTION_LIFETIME_SECONDS = 60;

/**
 * This Server's own identity, and the only thing about it that outlives a
 * restart: from the signing key every credential is earned afresh. There is
 * deliberately no field here a credential could be kept in, and the type is the
 * enforcement.
 *
 * spec: identity-and-authorization/client-credential-custody#own-key-is-the-only-thing-at-rest
 */
export interface ServerIdentity {
  /** Generated by this Server, never transmitted; only its public half is published. */
  readonly signingKey: CryptoKey;
  /** The domain this Server is operated from, as its registration records it. */
  readonly domain: string;
  /**
   * The one deployment this Server's assertions may be used at, by the
   * identifier that deployment publishes for itself — its `issuer` in the
   * document at `/.well-known/openid-configuration`.
   *
   * **Set this per deployment, and never to a value shared between them.** Why
   * a shared value would let one deployment impersonate this Server to another
   * is recorded at `assertionAudience` in
   * `packages/convex-host/convex/auth/deployment.ts`.
   */
  readonly issuanceEndpoint: string;
}

/**
 * Sign an assertion naming this Server, naming the platform's issuance endpoint
 * as the only place it may be used, and carrying an identifier unique to this
 * assertion.
 *
 * spec: identity-and-authorization/service-principal-assertions
 */
export function signAssertion(identity: ServerIdentity): Promise<string> {
  // Issuer and subject are both this Server: it asserts about itself and
  // nothing else. What human or team the resulting credential is for is settled
  // by the platform from the registration, never by a claim the Server makes.
  return new SignJWT({})
    .setProtectedHeader({ alg: ALG })
    .setIssuer(identity.domain)
    .setSubject(identity.domain)
    .setAudience(identity.issuanceEndpoint)
    .setJti(crypto.randomUUID())
    .setIssuedAt()
    .setExpirationTime(`${ASSERTION_LIFETIME_SECONDS}s`)
    .sign(identity.signingKey);
}

/**
 * The one team and one game a credential is for. Named once, when custody of it
 * begins: no call in this module takes a credential and a scope together, so
 * there is no way to present one team's or one game's credential under
 * another's name.
 *
 * spec: identity-and-authorization/game-credential-scope
 */
export interface GameScope {
  readonly teamId: string;
  readonly gameId: string;
}

/** Exchange a signed assertion for a game credential; supplied by the caller. */
export type Redeem = (assertion: string, scope: GameScope) => Promise<string>;

/** What a holder should do about the credential in hand. */
export type Renewal = "hold" | "renew" | "lapsed";

/**
 * Two thirds of the lifetime spent is when renewal begins — five minutes of
 * headroom on a fifteen-minute credential. The headroom has to cover several
 * attempts at the poll interval, because a brief outage is ridden out silently
 * (`#renewal-failure-is-quiet-until-it-bites`); renewing much earlier would
 * spend minting on nothing.
 */
const RENEW_AFTER_FRACTION = 2 / 3;

/**
 * The renewal decision, as a total function of the credential's age — pure and
 * exhaustive, so the discipline it encodes is testable without a clock.
 *
 * spec: identity-and-authorization/token-lifetime-and-refresh#renewal-is-proactive-never-reactive
 */
export function renewalAction(
  issuedAtSeconds: number,
  lifetimeSeconds: number,
  nowSeconds: number,
): Renewal {
  const age = nowSeconds - issuedAtSeconds;
  if (age >= lifetimeSeconds) return "lapsed";
  return age >= lifetimeSeconds * RENEW_AFTER_FRACTION ? "renew" : "hold";
}

/** Custody of the credential for one team in one game, for as long as it runs. */
export interface CredentialHandle {
  /** The credential in hand, or `undefined` while none is held. */
  readonly credential: () => string | undefined;
  /** Stop renewing and drop what is held. */
  readonly stop: () => void;
}

interface Held {
  readonly token: string;
  readonly issuedAtSeconds: number;
  readonly lifetimeSeconds: number;
}

function hold(token: string): Held {
  const { iat, exp } = decodeJwt(token);
  if (iat === undefined || exp === undefined) throw new Error("credential carries no lifetime");
  return { token, issuedAtSeconds: iat, lifetimeSeconds: exp - iat };
}

const nowSeconds = () => Math.floor(Date.now() / 1000);

/**
 * Begin holding a game credential for one team in one game, renewing ahead of
 * expiry until `stop`.
 *
 * `onLapse` fires once per lapse, not once per failed attempt, and retries
 * continue afterwards so a Server recovers on its own when the platform
 * returns.
 *
 * spec: identity-and-authorization/token-lifetime-and-refresh#renewal-failure-is-quiet-until-it-bites
 * spec: identity-and-authorization/client-credential-custody#memory-only
 */
export function holdGameCredential(
  identity: ServerIdentity,
  scope: GameScope,
  redeem: Redeem,
  onLapse: (cause: unknown) => void,
  pollMs = 30_000,
): CredentialHandle {
  // A closure variable, never written to storage, never logged, never handed to
  // anything but the caller that presents it. `stop` clears it, so teardown
  // leaves nothing behind.
  let held: Held | undefined;
  // Custody has ended. Checked *after* every await, not only before: a
  // redemption already in flight when `stop` is called resolves afterwards, and
  // assigning its result would hand a stopped handle a live credential that
  // then renews itself forever with no handle left to stop it.
  let stopped = false;
  // A tick is already running. `setInterval` does not wait for an async
  // callback, so a redemption slower than the poll interval would otherwise be
  // joined by a second, and two concurrent redemptions each spend a single-use
  // assertion and race to assign `held`.
  let ticking = false;

  const tick = async () => {
    if (stopped || ticking) return;
    const action = held
      ? renewalAction(held.issuedAtSeconds, held.lifetimeSeconds, nowSeconds())
      : "lapsed";
    if (action === "hold") return;
    ticking = true;
    try {
      const token = hold(await redeem(await signAssertion(identity), scope));
      // The guard that matters. Everything above may have taken a while.
      // spec: identity-and-authorization/client-credential-custody#memory-only
      if (!stopped) held = token;
    } catch (cause) {
      if (!stopped && action === "lapsed" && held !== undefined) {
        held = undefined;
        onLapse(cause);
      }
    } finally {
      ticking = false;
    }
  };

  const timer = setInterval(tick, pollMs);
  void tick();
  return {
    credential: () => held?.token,
    stop: () => {
      stopped = true;
      clearInterval(timer);
      held = undefined;
    },
  };
}
