// @ts-nocheck — generated; see scripts/generate-demo-bindings.mjs
// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AdmittedConnection = __t.object("AdmittedConnection", {
  connectionId: __t.connectionId(),
  role: __t.string(),
  subjectId: __t.string(),
  teamId: __t.string(),
});
export type AdmittedConnection = __Infer<typeof AdmittedConnection>;

export const DemoOwner = __t.object("DemoOwner", {
  key: __t.string(),
  ownerHex: __t.string(),
});
export type DemoOwner = __Infer<typeof DemoOwner>;

export const GameBinding = __t.object("GameBinding", {
  key: __t.string(),
  platformIssuer: __t.string(),
  gameId: __t.string(),
});
export type GameBinding = __Infer<typeof GameBinding>;

export const ParticipantTeam = __t.object("ParticipantTeam", {
  teamId: __t.string(),
});
export type ParticipantTeam = __Infer<typeof ParticipantTeam>;

export const RosterCoach = __t.object("RosterCoach", {
  key: __t.string(),
  userId: __t.string(),
  teamId: __t.string(),
});
export type RosterCoach = __Infer<typeof RosterCoach>;

export const RosterMember = __t.object("RosterMember", {
  userId: __t.string(),
  teamId: __t.string(),
});
export type RosterMember = __Infer<typeof RosterMember>;

export const TeamCounter = __t.object("TeamCounter", {
  teamId: __t.string(),
  count: __t.u32(),
});
export type TeamCounter = __Infer<typeof TeamCounter>;

