// @ts-nocheck — generated; see scripts/generate-demo-bindings.mjs
// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import IncrementReducer from "../increment_reducer";
import SeedGameReducer from "../seed_game_reducer";

export type IncrementParams = __Infer<typeof IncrementReducer>;
export type SeedGameParams = __Infer<typeof SeedGameReducer>;

